### ISSUE TITLE
Paid ngrok needed for this project? 

### ISSUE THREAD

**Issue by odoverdose** [daveebbelaar/airbnb-whatsapp-bot#6]
I've been following the instructions up until the ngrok section and noticed that a Pro or Enterprise tier is required to proceed. I've only used the free tier so far. Is there a way to use that to proceed? If not, might be a good idea to write in the requirements that a paid subscription is required to proceed. Thanks for a great video & repo, keep up the good work!

**Comment by daveebbelaar** [comment]
You don't need paid version. It can be done with the free version. Please check: https://github.com/daveebbelaar/python-whatsapp-bot?tab=readme-ov-file#step-3-configure-webhooks-to-receive-messages

**Comment by EdEn-D** [comment]
@daveebbelaar can you please verify this? I am not able to verify the domain using the free account. My suspicion is that it's because of the warning that users get when entering the domain for the first time which prevents the meta verification process to take place
